
DROP TABLE IF EXISTS PSER_TR_USUARIO_PULSSAR;
DROP TABLE IF EXISTS PSER_SEQ_USUARIO_PULSSAR;
DROP TABLE IF EXISTS PSER_TC_ROL_PULSSAR;
DROP TABLE IF EXISTS PSER_SEQ_ROL_PULSSAR;
DROP TABLE IF EXISTS PSER_TR_USER_ROL_PULSSAR;
DROP TABLE IF EXISTS PSER_SEQ_USER_ROL_PULSSAR;
DROP TABLE IF EXISTS PSER_TC_MENU_PAGINA;
DROP TABLE IF EXISTS PSER_SEQ_MENU_PAGINA;
DROP TABLE IF EXISTS PSER_TC_ROL_MENU;
DROP TABLE IF EXISTS PSER_SEQ_ROL_MENU;

DROP TABLE IF EXISTS PSER_TC_ORGANIZACION;
DROP TABLE IF EXISTS PSER_TR_CORREO_CORP_PULSSAR;
DROP TABLE IF EXISTS PSER_TR_CODIGO_CONFIMA_PULSSAR;
DROP TABLE IF EXISTS PSER_SEQ_COD_CONFIMA_PULSSAR;
DROP TABLE IF EXISTS PSER_TR_NICK_PULSSAR;
DROP TABLE IF EXISTS PSER_TC_RECHAZO_PULSSAR;
DROP TABLE IF EXISTS PSER_TR_RECHAZO_USER_PULSSAR;
DROP TABLE IF EXISTS PSER_TR_BLOQUEO_USER_PULSSAR;

DROP TABLE IF EXISTS PSER_TC_TURNO_ESTATUS;
DROP TABLE IF EXISTS PSER_TR_TURNO;
DROP TABLE IF EXISTS PSER_TR_FOLIO_PULSSAR;
DROP TABLE IF EXISTS PSER_TC_SERVICIO;

--Esquema Plataforma Operativa de Servicios
DROP TABLE IF EXISTS PSER_TC_MODULO_REPORTE;
DROP TABLE IF EXISTS PSER_TC_PROCESO_NEGOCIO;
DROP TABLE IF EXISTS PSER_TC_SUBPROCESO;
DROP TABLE IF EXISTS PSER_TC_TIPO_REPORTE;
DROP TABLE IF EXISTS PSER_TR_PARAMETRO_REPORTE;
DROP TABLE IF EXISTS PSER_TC_REPORTE_GENERICO;

--Masivos Plataforma Operativa de Servicios
DROP TABLE IF EXISTS PSER_TC_ESTADO_SOLICITUD;
DROP TABLE IF EXISTS PSER_TR_SOLICITUD_REPORTE; 
DROP TABLE IF EXISTS PSER_TB_BITACORA_REPORTE; 

CREATE TABLE IF NOT EXISTS PSER_TR_USUARIO_PULSSAR (
	ID_USUARIO_PULSSAR NUMBER(16, 0) NOT NULL,
	CH_USUARIO VARCHAR2(100 CHAR) NOT NULL,
	CH_NOMBRE VARCHAR2(50 CHAR) NOT NULL,
	CH_APELLIDO_PATERNO VARCHAR2(50 CHAR) NOT NULL,
	CH_APELLIDO_MATERNO VARCHAR2(50 CHAR),
	CH_EMAIL VARCHAR2(50 CHAR),
	CH_CELULAR VARCHAR2(10 CHAR),
	CV_ORGANIZACION VARCHAR2(4 CHAR) NOT NULL,
	CH_ESTATUS VARCHAR2(2 CHAR) NOT NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	CH_SUCURSAL VARCHAR2(20 CHAR),
	CH_CLAVE_OFICINA VARCHAR2(50 CHAR),
	NU_IDENTIFICADOR_ZONA NUMBER(16, 0),
	PRIMARY KEY (ID_USUARIO_PULSSAR) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_USUARIO_PULSSAR START WITH 50;

CREATE TABLE IF NOT EXISTS PSER_TC_ROL_PULSSAR (
	ID_ROL_PULSSAR NUMBER(16, 0) NOT NULL,
	CV_ROL_PULSSAR VARCHAR2(4 CHAR) NOT NULL,
	CH_DESC_ROL_PULSSAR VARCHAR2(50 CHAR) NOT NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	CH_AFORE VARCHAR2(3 CHAR) NOT NULL,
	PRIMARY KEY (ID_ROL_PULSSAR) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_ROL_PULSSAR START WITH 50;

CREATE TABLE IF NOT EXISTS PSER_TR_USER_ROL_PULSSAR (
	ID_USUARIO_PULSSAR NUMBER(16, 0) NOT NULL,
	NU_ESTATUS NUMBER(1, 0) NOT NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	ID_USER_ROL_PULSSAR NUMBER(16, 0) NOT NULL,
	ID_ROL_PULSSAR NUMBER(16, 0) NOT NULL,
	PRIMARY KEY (ID_USER_ROL_PULSSAR) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_USER_ROL_PULSSAR START WITH 30;

CREATE TABLE IF NOT EXISTS PSER_TC_MENU_PAGINA (
	ID_MENU_PAGINA NUMBER(16, 0) NOT NULL , 
	NU_PAGINA__PRINCIPAL NUMBER(1, 0) NOT NULL , 
	CH_RUTA VARCHAR2(100 CHAR) NOT NULL , 
	CH_DESC_MENU_PAGINA VARCHAR2(50 CHAR) NOT NULL , 
	CH_IMAGEN VARCHAR2(50 CHAR) NOT NULL , 
	FC_CONTROL DATE NOT NULL , 
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL ,
	PRIMARY KEY (ID_MENU_PAGINA) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_MENU_PAGINA START WITH 30;

CREATE TABLE IF NOT EXISTS PSER_TC_ROL_MENU (
	ID_ROL_MENU NUMBER(16, 0) NOT NULL, 
	ID_ROL_PULSSAR NUMBER(16, 0) NOT NULL,  
	ID_MENU_PAGINA NUMBER(16, 0) NOT NULL,  
	FC_CONTROL DATE NOT NULL, 
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR), 
	PRIMARY KEY (ID_ROL_MENU) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_ROL_MENU START WITH 30;

CREATE TABLE PSER_TR_BLOQUEO_USER_PULSSAR (
	 ID_BLOQUEO_USER_PULSSAR NUMBER(16, 0) NOT NULL, 
	 ID_USUARIO_PULSSAR NUMBER(16, 0) NOT NULL, 
	 FC_VIGENCIA DATE, 
	 CH_ESATUS VARCHAR2(2 CHAR) NOT NULL, 
	 NU_INTENTOS NUMBER(1, 0) NOT NULL, 
	 FC_CONTROL DATE NOT NULL, 
	 CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	 PRIMARY KEY (ID_BLOQUEO_USER_PULSSAR) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_BLOQ_USER_PULSSAR START WITH 20;

CREATE TABLE IF NOT EXISTS PSER_TR_RECHAZO_USER_PULSSAR (
	ID_RECHAZO_USER_PULSSAR NUMBER(16, 0) NOT NULL,
	CH_USUARIO VARCHAR2(100 CHAR) NOT NULL,
	CH_NOMBRE VARCHAR2(50 CHAR) NOT NULL,
	CH_APELLIDO_PATERNO VARCHAR2(50 CHAR) NOT NULL,
	CH_APELLIDO_MATERNO VARCHAR2(50 CHAR),
	CH_EMAIL VARCHAR2(50 CHAR),
	CH_CELULAR VARCHAR2(10 CHAR) NOT NULL,
	CV_ORGANIZACION VARCHAR2(4 CHAR),
	CH_NICK_USER VARCHAR2(20 CHAR),
	ID_RECHAZO_PULSSAR NUMBER(16, 0) NOT NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	PRIMARY KEY (ID_RECHAZO_USER_PULSSAR) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_RECHAZO_USER_PULSSAR START WITH 30;

CREATE TABLE IF NOT EXISTS PSER_TC_ORGANIZACION (
	CV_ORGANIZACION VARCHAR2(4 CHAR) NOT NULL,
	CH_DESC_ORGANIZACION VARCHAR2(50 CHAR) NOT NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	PRIMARY KEY (CV_ORGANIZACION) );

CREATE TABLE IF NOT EXISTS PSER_TR_CORREO_CORP_PULSSAR (
	CV_ORGANIZACION VARCHAR2(4 CHAR) NOT NULL,
	CH_EMAIL_CORP VARCHAR2(50 CHAR) NOT NULL,
	NU_ESTATUS NUMBER(1, 0) NOT NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	PRIMARY KEY (CV_ORGANIZACION, CH_EMAIL_CORP));

CREATE TABLE IF NOT EXISTS PSER_TR_CODIGO_CONFIMA_PULSSAR (
	ID_CODIGO_CONFIMA_PULSSAR NUMBER(16, 0) NOT NULL,
	ID_USUARIO_PULSSAR NUMBER(16, 0) NOT NULL,
	CH_FOLIO VARCHAR2(20 CHAR) NOT NULL,
	CH_CODIGO_CONFIRMACION VARCHAR2(4 CHAR) NOT NULL,
	NU_ESTATUS NUMBER(1, 0) NOT NULL,
	CH_TIPO_CODIGO VARCHAR2(2 CHAR) NOT NULL,
	FC_VIGENCIA DATE NOT NULL,
	FC_USO DATE NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	NU_INTENTOS NUMBER(1, 0) NULL,
	PRIMARY KEY (ID_CODIGO_CONFIMA_PULSSAR) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_COD_CONFIMA_PULSSAR START WITH 50;

CREATE TABLE IF NOT EXISTS PSER_TR_NICK_PULSSAR (
	ID_USUARIO_PULSSAR NUMBER(16, 0) NOT NULL,
	CH_NICK_USUARIO VARCHAR2(20 CHAR) NOT NULL,
	NU_ESTATUS NUMBER(1, 0) NOT NULL,
	FC_CONTROL DATE NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL,
	PRIMARY KEY (ID_USUARIO_PULSSAR, CH_NICK_USUARIO) );
	
CREATE TABLE IF NOT EXISTS PSER_TC_RECHAZO_PULSSAR(
 	 ID_RECHAZO_PULSSAR NUMBER(16, 0) NOT NULL,
	 CV_RECHAZO_PULSSAR VARCHAR2(4 CHAR) NOT NULL, 
	 CV_ORGANIZACION VARCHAR2(4 CHAR) NOT NULL, 
	 CH_TITULO_MENSAJE VARCHAR2(100 CHAR) NOT NULL, 
	 CH_MENSAJE VARCHAR2(150 CHAR) NOT NULL, 
	 NU_ESTATUS NUMBER(2, 0) NOT NULL, 
	 FC_CONTROL DATE NOT NULL, 
  	 CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL, 
  	 PRIMARY KEY (ID_RECHAZO_PULSSAR) );
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_RECHAZO_PULSSAR START WITH 30;

-- ADMINISTRACIÓN DE TURNOS.
CREATE TABLE IF NOT EXISTS PSER_TC_SERVICIO (
    ID_SERVICIO            NUMBER(8,0)        NOT NULL,
    CV_SERVICIO            VARCHAR2(20 CHAR)  NOT NULL,
    CH_DESC_SERVICIO       VARCHAR2(200 CHAR) NOT NULL,
    CV_TIPO_SERVICIO       VARCHAR2(2 CHAR)   NOT NULL,
    NU_ESTATUS             NUMBER(1,0)        NOT NULL,
    FC_CONTROL             DATE               NOT NULL,
    CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR)  NOT NULL,
    PRIMARY KEY (ID_SERVICIO)
);

CREATE TABLE IF NOT EXISTS PSER_TR_FOLIO_PULSSAR (
	ID_FOLIO_PULSSAR       NUMBER(16,0)        NOT NULL,
	ID_SERVICIO            NUMBER(8,0)         NOT NULL,
	ID_USUARIO_PULSSAR     NUMBER(16,0)        NOT NULL,
	CH_FOLIO               VARCHAR2(20 CHAR)   NOT NULL,
	CH_DESCRIPCION         VARCHAR2(2000 CHAR) NULL,
	CH_SUCURSAL            VARCHAR2(16 CHAR)   NOT NULL,
	NSS                    VARCHAR2(11 CHAR)   NULL,
	CURP                   VARCHAR2(18 CHAR)   NULL,
	NU_ESTATUS             NUMBER(1,0)         NOT NULL,
	FC_GENERACION_FOLIO    DATE                NOT NULL,
	FC_CONTROL             DATE                NOT NULL,
	CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR)   NOT NULL,
	FC_LLEGADA             DATE                NULL,
	FC_CIERRE_FOLIO        DATE                NULL,
	ID_FOLIO_PULSSAR_PADRE NUMBER(16,0)        NULL,
	NU_ESTATUS_PADRE       NUMBER(1,0)         NULL,
	CH_TIPO_SOLICITANTE    VARCHAR2(2 CHAR)    NULL,
	PRIMARY KEY (ID_FOLIO_PULSSAR)
);

CREATE TABLE IF NOT EXISTS PSER_TC_TURNO_ESTATUS (
   CV_TURNO_ESTATUS       VARCHAR2(2 CHAR)  NOT NULL,
   CH_DESC_TURNO_ESTATUS  VARCHAR2(50 CHAR) NOT NULL,
   FC_CONTROL             DATE              NOT NULL,
   CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NULL,
    PRIMARY KEY (CV_TURNO_ESTATUS)
);

CREATE TABLE IF NOT EXISTS PSER_TR_TURNO (
   ID_TURNO                 NUMBER(16,0)       NOT NULL,
   NU_CUS                   NUMBER(14,0)       NULL,
   CURP                     VARCHAR2(18 CHAR)  NULL,
   NSS                      VARCHAR2(11 CHAR)  NULL,
   FC_CITA_CUS              TIMESTAMP          NULL,
   CH_NOMBRE_TRAB           VARCHAR2(50 CHAR)  NOT NULL,
   CH_APELLIDO_PATERNO_TRAB VARCHAR2(50 CHAR)  NOT NULL,
   CH_APELLIDO_MATERNO_TRAB VARCHAR2(50 CHAR)  NOT NULL,
   ID_SERVICIO              NUMBER(8,0)        NOT NULL,
   CH_SERVICIOS_REALIZADOS  VARCHAR2(150 CHAR) NULL,
   ID_USUARIO_PULSSAR       NUMBER(16,0)       NOT NULL,
   CH_FOLIO_ATENCION        VARCHAR2(50 CHAR)  NULL,
   ID_FOLIO_PULSSAR         NUMBER(16,0)       NOT NULL,
   CH_INDICADOR_CITA        VARCHAR2(2 CHAR)   NULL,
   CV_TURNO_ESTATUS         VARCHAR2(2 CHAR)   NOT NULL,
   FC_REGISTRO              TIMESTAMP          NULL,
   FC_INICIO_ATENCION       TIMESTAMP          NULL,
   FC_FIN_ATENCION          TIMESTAMP          NULL,
   CH_EMAIL                 VARCHAR2(50 CHAR)  NULL,
   CH_CELULAR               VARCHAR2(10 CHAR)  NULL,
   FC_CONTROL               TIMESTAMP          NOT NULL,
   CH_USUARIO_MODIFICADOR   VARCHAR2(50 CHAR)  NOT NULL,
   CH_FOLIO_SERVICIO        VARCHAR2(6 CHAR)   NOT NULL,
   CH_AFORE	                VARCHAR2(3 CHAR)   NULL,
   PRIMARY KEY (ID_TURNO),
   FOREIGN KEY (CV_TURNO_ESTATUS)   REFERENCES PSER_TC_TURNO_ESTATUS(CV_TURNO_ESTATUS),
   FOREIGN KEY (ID_USUARIO_PULSSAR) REFERENCES PSER_TR_USUARIO_PULSSAR(ID_USUARIO_PULSSAR),
   FOREIGN KEY (ID_FOLIO_PULSSAR)   REFERENCES PSER_TR_FOLIO_PULSSAR(ID_FOLIO_PULSSAR),
   FOREIGN KEY (ID_SERVICIO)        REFERENCES PSER_TC_SERVICIO(ID_SERVICIO)
);
CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_TURNO START WITH 1;

--Plataforma de servicios operativa
CREATE TABLE IF NOT EXISTS PSER_TC_MODULO_REPORTE 
(
  ID_MODULO_REPORTE NUMBER(3, 0) NOT NULL 
, CH_NOMBRE_MODULO_REP VARCHAR2(50 CHAR) NOT NULL 
, NU_ACTIVO NUMBER (3 ,0) 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL 

,PRIMARY KEY(ID_MODULO_REPORTE) 
);

CREATE TABLE IF NOT EXISTS PSER_TC_PROCESO_NEGOCIO 
(
  ID_PROCESO_NEGOCIO NUMBER(6, 0) NOT NULL 
, ID_MODULO_REPORTE NUMBER(6, 0) NOT NULL 
, CH_NOMBRE_PROCESO VARCHAR2(100 CHAR) NOT NULL 
, NU_ACTIVO NUMBER(1, 0) NOT NULL 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL 

,PRIMARY KEY(ID_PROCESO_NEGOCIO)
);

CREATE TABLE IF NOT EXISTS PSER_TC_SUBPROCESO 
(
  ID_SUBPROCESO NUMBER(6, 0) NOT NULL 
, ID_PROCESO_NEGOCIO NUMBER(6, 0) NOT NULL 
, CH_NOMBRE_SUBPROCESO VARCHAR2(100 CHAR) NOT NULL 
, NU_ACTIVO NUMBER(1, 0) NOT NULL 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR)

,PRIMARY KEY(ID_SUBPROCESO)
);

CREATE TABLE IF NOT EXISTS PSER_TC_TIPO_REPORTE
(
  ID_TIPO_REPORTE NUMBER(6, 0) NOT NULL 
, CH_DESCRIPCION VARCHAR2(100 CHAR) NOT NULL 
, NU_ACTIVO NUMBER(1, 0) NOT NULL 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL
, NU_BATCH_LINEA NUMBER(1, 0) DEFAULT 0 NOT NULL 

,PRIMARY KEY(ID_TIPO_REPORTE)
);

CREATE TABLE IF NOT EXISTS PSER_TR_PARAMETRO_REPORTE 
(
  ID_PARAMETRO_REPORTE NUMBER(6, 0) NOT NULL 
, ID_REPORTE_GENERICO NUMBER(6, 0) NOT NULL 
, NU_SECUENCIA NUMBER(4, 0) NOT NULL 
, CH_NOMBRE VARCHAR2(30 CHAR) NOT NULL 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL
, CH_SECCION_PARAMETRO VARCHAR2(4 CHAR) NOT NULL 
, CH_TIPO_DATO VARCHAR2(3 CHAR) NOT NULL 
, CH_TIPO_PARAMETRO VARCHAR2(3 CHAR) NOT NULL 
, NU_DIAS_MAXIMO NUMBER(9, 0) NULL 

,PRIMARY KEY(ID_PARAMETRO_REPORTE)
) ;

CREATE TABLE IF NOT EXISTS PSER_TC_REPORTE_GENERICO 
(
  ID_REPORTE_GENERICO NUMBER(6, 0) NOT NULL 
, ID_SUBPROCESO NUMBER(6, 0) NOT NULL 
, ID_TIPO_REPORTE NUMBER(6, 0) NOT NULL 
, CH_NOMBRE_REPORTE VARCHAR2(100 CHAR) NOT NULL 
, NU_ACTIVO NUMBER(1, 0) NOT NULL 
, CH_CONSULTA VARCHAR2(4000 CHAR) 
, CH_ESQUEMA VARCHAR2(50 CHAR) NOT NULL 
, CH_ENCABEZADO VARCHAR2(4000 CHAR) 
, NU_FILTRO_NSS NUMBER(1, 0) 
, NU_FILTRO_CURP NUMBER(1, 0) 
, NU_FILTRO_RANGO_FC NUMBER(1, 0) 
, NU_FILTRO_ID_PROCESAR NUMBER(1, 0) 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL
, ID_REPORTE_GENERICO_PADRE NUMBER(6, 0) 
, NU_ORDEN NUMBER(2, 0) 
, CH_NOMBRE_ARCHIVO_REPORTE VARCHAR2(50 CHAR) 
, CH_URL VARCHAR2(500 CHAR)

,PRIMARY KEY(ID_REPORTE_GENERICO)
);

CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_SOLICITUD_REPORTE;
CREATE TABLE IF NOT EXISTS PSER_TR_SOLICITUD_REPORTE 
(
  ID_SOLICITUD_REPORTE NUMBER(16, 0) NOT NULL 
, CH_NUMERO_SOLICITUD_REPORTE VARCHAR2(50 CHAR) NOT NULL 
, ID_REPORTE_GENERICO NUMBER(6, 0) NOT NULL 
, ID_ESTADO_SOLICITUD NUMBER(3, 0) NOT NULL 
, FC_ENVIO DATE NOT NULL 
, FC_PROCESO DATE 
, CH_RUTA_ARCHIVO_SOLICITUD VARCHAR2(200 CHAR) 
, CH_NOMBRE_ARCHIVO_SOLICITUD VARCHAR2(200 CHAR) 
, CH_RUTA_ARCHIVO_RESPUESTA VARCHAR2(200 CHAR) 
, CH_NOMBRE_ARCHIVO_RESPUESTA VARCHAR2(200 CHAR) 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL 
, ID_BITACORA_REPORTE NUMBER(12, 0) 

, PRIMARY KEY (ID_SOLICITUD_REPORTE)
);


CREATE TABLE IF NOT EXISTS PSER_TC_ESTADO_SOLICITUD 
(
  ID_ESTADO_SOLICITUD NUMBER(3, 0) NOT NULL 
, CH_DESC_ESTADO_SOLICITUD VARCHAR2(30 CHAR) NOT NULL 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL 

,PRIMARY KEY(ID_ESTADO_SOLICITUD)
);

CREATE SEQUENCE IF NOT EXISTS PSER_SEQ_BITACORA_REPORTE;
CREATE TABLE IF NOT EXISTS PSER_TB_BITACORA_REPORTE 
(
  ID_BITACORA_REPORTE NUMBER(12, 0) NOT NULL 
, ID_REPORTE_GENERICO NUMBER(6, 0) NOT NULL 
, CH_USUARIO VARCHAR2(50 CHAR) NOT NULL 
, FC_EJECUCION DATE NOT NULL 
, CH_PARAMETRO VARCHAR2(4000 CHAR) NOT NULL 
, NU_EXPORT_REPORTE NUMBER(1, 0) 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL 
, CH_IP_ORIGEN VARCHAR2(13 CHAR) NOT NULL

,PRIMARY KEY(ID_BITACORA_REPORTE)
);

CREATE TABLE IF NOT EXISTS PSER_TR_ROL_REPORTE 
(
  ID_ROL_REPORTE NUMBER(16, 0) NOT NULL 
, CV_ROL_PULSSAR VARCHAR2(4 CHAR) NOT NULL 
, ID_REPORTE_GENERICO NUMBER(6, 0) NOT NULL 
, NU_ACTIVO NUMBER(1, 0) NOT NULL 
, FC_CONTROL DATE NOT NULL 
, CH_USUARIO_MODIFICADOR VARCHAR2(50 CHAR) NOT NULL 
)  
