//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.27 at 05:08:42 PM CDT 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo.agm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AyudaGastosMatrimonio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AyudaGastosMatrimonio"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nss" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="curp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fechaSolicitud" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="claveAfore" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="claveSexoConyuge" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="entidadEmisionActaMatrimonio" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AyudaGastosMatrimonio", propOrder = {
    "nss",
    "curp",
    "fechaSolicitud",
    "claveAfore",
    "claveSexoConyuge",
    "entidadEmisionActaMatrimonio"
})
public class AyudaGastosMatrimonio {

    @XmlElement(required = true)
    protected String nss;
    protected String curp;
    @XmlElement(required = true)
    protected String fechaSolicitud;
    @XmlElement(required = true)
    protected String claveAfore;
    @XmlElement(required = true)
    protected String claveSexoConyuge;
    @XmlElement(required = true)
    protected String entidadEmisionActaMatrimonio;

    /**
     * Gets the value of the nss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNss() {
        return nss;
    }

    /**
     * Sets the value of the nss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNss(String value) {
        this.nss = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurp() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurp(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the fechaSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaSolicitud() {
        return fechaSolicitud;
    }

    /**
     * Sets the value of the fechaSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaSolicitud(String value) {
        this.fechaSolicitud = value;
    }

    /**
     * Gets the value of the claveAfore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveAfore() {
        return claveAfore;
    }

    /**
     * Sets the value of the claveAfore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveAfore(String value) {
        this.claveAfore = value;
    }

    /**
     * Gets the value of the claveSexoConyuge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveSexoConyuge() {
        return claveSexoConyuge;
    }

    /**
     * Sets the value of the claveSexoConyuge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveSexoConyuge(String value) {
        this.claveSexoConyuge = value;
    }

    /**
     * Gets the value of the entidadEmisionActaMatrimonio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidadEmisionActaMatrimonio() {
        return entidadEmisionActaMatrimonio;
    }

    /**
     * Sets the value of the entidadEmisionActaMatrimonio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidadEmisionActaMatrimonio(String value) {
        this.entidadEmisionActaMatrimonio = value;
    }

}
