//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.27 at 05:08:42 PM CDT 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo.agm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertificacionAGM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertificacionAGM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nss" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="curp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="delegacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="subdelegacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="umf" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="apellidoPaterno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="apellidoMaterno" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="prestacionSolicitada" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaSolicitud" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numeroResolucion" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="claveResolucion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="claveMensajePROCESARA" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="claveMensajePROCESARB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaPrestTramite" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="salarioBaseCotizacionIncisoA" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="salarioPromedioCotizacionIncisoB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="retiroComplementario" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaBaja" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertificacionAGM", propOrder = {
    "nss",
    "curp",
    "delegacion",
    "subdelegacion",
    "umf",
    "apellidoPaterno",
    "apellidoMaterno",
    "nombre",
    "prestacionSolicitada",
    "fechaSolicitud",
    "numeroResolucion",
    "claveResolucion",
    "claveMensajePROCESARA",
    "claveMensajePROCESARB",
    "fechaPrestTramite",
    "salarioBaseCotizacionIncisoA",
    "salarioPromedioCotizacionIncisoB",
    "retiroComplementario",
    "fechaBaja"
})
public class CertificacionAGM {

    @XmlElement(required = true)
    protected String nss;
    @XmlElement(required = true, nillable = true)
    protected String curp;
    @XmlElement(required = true)
    protected String delegacion;
    @XmlElement(required = true)
    protected String subdelegacion;
    @XmlElement(required = true, nillable = true)
    protected String umf;
    @XmlElement(required = true)
    protected String apellidoPaterno;
    @XmlElement(required = true, nillable = true)
    protected String apellidoMaterno;
    @XmlElement(required = true)
    protected String nombre;
    @XmlElement(required = true)
    protected String prestacionSolicitada;
    @XmlElement(required = true)
    protected String fechaSolicitud;
    protected int numeroResolucion;
    @XmlElement(required = true)
    protected String claveResolucion;
    @XmlElement(required = true)
    protected String claveMensajePROCESARA;
    @XmlElement(required = true)
    protected String claveMensajePROCESARB;
    @XmlElement(required = true, nillable = true)
    protected String fechaPrestTramite;
    @XmlElement(required = true)
    protected String salarioBaseCotizacionIncisoA;
    @XmlElement(required = true)
    protected String salarioPromedioCotizacionIncisoB;
    @XmlElement(required = true)
    protected String retiroComplementario;
    @XmlElement(required = true)
    protected String fechaBaja;

    /**
     * Gets the value of the nss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNss() {
        return nss;
    }

    /**
     * Sets the value of the nss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNss(String value) {
        this.nss = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurp() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurp(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the delegacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegacion() {
        return delegacion;
    }

    /**
     * Sets the value of the delegacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegacion(String value) {
        this.delegacion = value;
    }

    /**
     * Gets the value of the subdelegacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubdelegacion() {
        return subdelegacion;
    }

    /**
     * Sets the value of the subdelegacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubdelegacion(String value) {
        this.subdelegacion = value;
    }

    /**
     * Gets the value of the umf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmf() {
        return umf;
    }

    /**
     * Sets the value of the umf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmf(String value) {
        this.umf = value;
    }

    /**
     * Gets the value of the apellidoPaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoPaterno() {
        return apellidoPaterno;
    }

    /**
     * Sets the value of the apellidoPaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoPaterno(String value) {
        this.apellidoPaterno = value;
    }

    /**
     * Gets the value of the apellidoMaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoMaterno() {
        return apellidoMaterno;
    }

    /**
     * Sets the value of the apellidoMaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoMaterno(String value) {
        this.apellidoMaterno = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the prestacionSolicitada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrestacionSolicitada() {
        return prestacionSolicitada;
    }

    /**
     * Sets the value of the prestacionSolicitada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrestacionSolicitada(String value) {
        this.prestacionSolicitada = value;
    }

    /**
     * Gets the value of the fechaSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaSolicitud() {
        return fechaSolicitud;
    }

    /**
     * Sets the value of the fechaSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaSolicitud(String value) {
        this.fechaSolicitud = value;
    }

    /**
     * Gets the value of the numeroResolucion property.
     * 
     */
    public int getNumeroResolucion() {
        return numeroResolucion;
    }

    /**
     * Sets the value of the numeroResolucion property.
     * 
     */
    public void setNumeroResolucion(int value) {
        this.numeroResolucion = value;
    }

    /**
     * Gets the value of the claveResolucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveResolucion() {
        return claveResolucion;
    }

    /**
     * Sets the value of the claveResolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveResolucion(String value) {
        this.claveResolucion = value;
    }

    /**
     * Gets the value of the claveMensajePROCESARA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveMensajePROCESARA() {
        return claveMensajePROCESARA;
    }

    /**
     * Sets the value of the claveMensajePROCESARA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveMensajePROCESARA(String value) {
        this.claveMensajePROCESARA = value;
    }

    /**
     * Gets the value of the claveMensajePROCESARB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveMensajePROCESARB() {
        return claveMensajePROCESARB;
    }

    /**
     * Sets the value of the claveMensajePROCESARB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveMensajePROCESARB(String value) {
        this.claveMensajePROCESARB = value;
    }

    /**
     * Gets the value of the fechaPrestTramite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaPrestTramite() {
        return fechaPrestTramite;
    }

    /**
     * Sets the value of the fechaPrestTramite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaPrestTramite(String value) {
        this.fechaPrestTramite = value;
    }

    /**
     * Gets the value of the salarioBaseCotizacionIncisoA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalarioBaseCotizacionIncisoA() {
        return salarioBaseCotizacionIncisoA;
    }

    /**
     * Sets the value of the salarioBaseCotizacionIncisoA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalarioBaseCotizacionIncisoA(String value) {
        this.salarioBaseCotizacionIncisoA = value;
    }

    /**
     * Gets the value of the salarioPromedioCotizacionIncisoB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalarioPromedioCotizacionIncisoB() {
        return salarioPromedioCotizacionIncisoB;
    }

    /**
     * Sets the value of the salarioPromedioCotizacionIncisoB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalarioPromedioCotizacionIncisoB(String value) {
        this.salarioPromedioCotizacionIncisoB = value;
    }

    /**
     * Gets the value of the retiroComplementario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetiroComplementario() {
        return retiroComplementario;
    }

    /**
     * Sets the value of the retiroComplementario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetiroComplementario(String value) {
        this.retiroComplementario = value;
    }

    /**
     * Gets the value of the fechaBaja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaBaja() {
        return fechaBaja;
    }

    /**
     * Sets the value of the fechaBaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaBaja(String value) {
        this.fechaBaja = value;
    }

}
