//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.27 at 05:08:42 PM CDT 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo.agm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Respuesta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Respuesta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="exito" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="claveError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="descripcionError" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resolucion" type="{http://certificacion.service.agm.ctirss.imss.gob.mx/}ResolucionAGM"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Respuesta", propOrder = {
    "exito",
    "claveError",
    "descripcionError",
    "resolucion"
})
public class Respuesta {

    protected int exito;
    @XmlElement(required = true, nillable = true)
    protected String claveError;
    @XmlElement(required = true, nillable = true)
    protected String descripcionError;
    @XmlElement(required = true, nillable = true)
    protected ResolucionAGM resolucion;

    /**
     * Gets the value of the exito property.
     * 
     */
    public int getExito() {
        return exito;
    }

    /**
     * Sets the value of the exito property.
     * 
     */
    public void setExito(int value) {
        this.exito = value;
    }

    /**
     * Gets the value of the claveError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveError() {
        return claveError;
    }

    /**
     * Sets the value of the claveError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveError(String value) {
        this.claveError = value;
    }

    /**
     * Gets the value of the descripcionError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionError() {
        return descripcionError;
    }

    /**
     * Sets the value of the descripcionError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionError(String value) {
        this.descripcionError = value;
    }

    /**
     * Gets the value of the resolucion property.
     * 
     * @return
     *     possible object is
     *     {@link ResolucionAGM }
     *     
     */
    public ResolucionAGM getResolucion() {
        return resolucion;
    }

    /**
     * Sets the value of the resolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResolucionAGM }
     *     
     */
    public void setResolucion(ResolucionAGM value) {
        this.resolucion = value;
    }

}
