//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 12:26:30 PM CST 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ArrayOf_tns1_LayoutRespuestaHistoricoRetiros complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOf_tns1_LayoutRespuestaHistoricoRetiros"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="layoutRespuestaHistoricoRetiros" type="{http://dto.ws.retiros.procesar.com}LayoutRespuestaHistoricoRetiros" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class ArregloRespuestaHistoricoRetiros  implements Serializable{

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -3011250883595208584L;
	private List<RespuestaHistoricoRetiros> layoutRespuestaHistoricoRetiros;

	/**
	 * Gets the value of the layoutRespuestaHistoricoRetiros property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the layoutRespuestaHistoricoRetiros property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getLayoutRespuestaHistoricoRetiros().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RespuestaHistoricoRetiros }
	 * @return List<RespuestaHistoricoRetiros>
	 * 
	 * 
	 */
	public List<RespuestaHistoricoRetiros> getLayoutRespuestaHistoricoRetiros() {
		if (layoutRespuestaHistoricoRetiros == null) {
			layoutRespuestaHistoricoRetiros = new ArrayList<>();
		}
		return this.layoutRespuestaHistoricoRetiros;
	}

	/* La documentación de este método se encuentra en la clase o interface que
	 * lo declara  (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ArregloRespuestaHistoricoRetiros [getLayoutRespuestaHistoricoRetiros()=");
		builder.append(getLayoutRespuestaHistoricoRetiros());
		builder.append("]");
		return builder.toString();
	}

}
