//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 12:26:30 PM CST 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo;

import java.io.Serializable;
import java.util.Date;


/**
 * <p>Java class for LayoutCalculoMontoReintegrar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutCalculoMontoReintegrar"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="claveAfore" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaRetiro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nssTrabajador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numeroResolucion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numeroSemanasReintegrar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class CalculoMontoReintegrar  implements Serializable{

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 6236752558823557863L;
	protected String claveAfore;
	protected Date fechaRetiro;
	protected String nssTrabajador;
	protected String numeroResolucion;
	protected String numeroSemanasReintegrar;

	/**
	 * Gets the value of the claveAfore property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getClaveAfore() {
		return claveAfore;
	}

	/**
	 * Sets the value of the claveAfore property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setClaveAfore(String value) {
		this.claveAfore = value;
	}

	/**
	 * Gets the value of the fechaRetiro property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public Date getFechaRetiro() {
		return fechaRetiro;
	}

	/**
	 * Sets the value of the fechaRetiro property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setFechaRetiro(Date value) {
		this.fechaRetiro = value;
	}

	/**
	 * Gets the value of the nssTrabajador property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getNssTrabajador() {
		return nssTrabajador;
	}

	/**
	 * Sets the value of the nssTrabajador property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setNssTrabajador(String value) {
		this.nssTrabajador = value;
	}

	/**
	 * Gets the value of the numeroResolucion property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getNumeroResolucion() {
		return numeroResolucion;
	}

	/**
	 * Sets the value of the numeroResolucion property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setNumeroResolucion(String value) {
		this.numeroResolucion = value;
	}

	/**
	 * Gets the value of the numeroSemanasReintegrar property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getNumeroSemanasReintegrar() {
		return numeroSemanasReintegrar;
	}

	/**
	 * Sets the value of the numeroSemanasReintegrar property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setNumeroSemanasReintegrar(String value) {
		this.numeroSemanasReintegrar = value;
	}

	/* La documentación de este método se encuentra en la clase o interface que
	 * lo declara  (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CalculoMontoReintegrar [getClaveAfore()=");
		builder.append(getClaveAfore());
		builder.append(", getFechaRetiro()=");
		builder.append(getFechaRetiro());
		builder.append(", getNssTrabajador()=");
		builder.append(getNssTrabajador());
		builder.append(", getNumeroResolucion()=");
		builder.append(getNumeroResolucion());
		builder.append(", getNumeroSemanasReintegrar()=");
		builder.append(getNumeroSemanasReintegrar());
		builder.append("]");
		return builder.toString();
	}

}
