//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.09 at 12:03:57 PM CDT 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for consultarKardexSalida complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultarKardexSalida"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="resultadoOperacion" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}resultadoOperacion"/&gt;
 *         &lt;element name="diagnosticoProcesar" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_3" minOccurs="0"/&gt;
 *         &lt;element name="nss" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}nss_op" minOccurs="0"/&gt;
 *         &lt;element name="curp" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}curp"/&gt;
 *         &lt;element name="nombreBdnsar" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_50" minOccurs="0"/&gt;
 *         &lt;element name="apellidoPaternoBdnsar" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_50" minOccurs="0"/&gt;
 *         &lt;element name="apellidoMaternoBdnsar" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_50" minOccurs="0"/&gt;
 *         &lt;element name="fechaNacimiento" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_10" minOccurs="0"/&gt;
 *         &lt;element name="genero" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_2" minOccurs="0"/&gt;
 *         &lt;element name="entidadNacimiento" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_2" minOccurs="0"/&gt;
 *         &lt;element name="curpBdnsar" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_18" minOccurs="0"/&gt;
 *         &lt;element name="salarioDiarioIntegrado" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_15_0" minOccurs="0"/&gt;
 *         &lt;element name="periodoPago" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_6" minOccurs="0"/&gt;
 *         &lt;element name="indicadorRetiroDesempleo" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_2" minOccurs="0"/&gt;
 *         &lt;element name="listaIcefasDisponiblesSaldo" type="{http://www.procesar.com.mx/AdmonCuenta/ConsultarKardexTrabajador/consultarKardex/}listaIcefasDisponiblesSaldo" minOccurs="0"/&gt;
 *         &lt;element name="nombreImss" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_0_120" minOccurs="0"/&gt;
 *         &lt;element name="nombreRenapo" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_50" minOccurs="0"/&gt;
 *         &lt;element name="apellidoPaternoRenapo" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_50" minOccurs="0"/&gt;
 *         &lt;element name="apellidoMaternoRenapo" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_50" minOccurs="0"/&gt;
 *         &lt;element name="estatusCURPDuplicada" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_2" minOccurs="0"/&gt;
 *         &lt;element name="listaCurpHistoricas" type="{http://www.procesar.com.mx/AdmonCuenta/ConsultarKardexTrabajador/consultarKardex/}curpHistoricas" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarKardexSalida", propOrder = {
    "resultadoOperacion",
    "diagnosticoProcesar",
    "nss",
    "curp",
    "nombreBdnsar",
    "apellidoPaternoBdnsar",
    "apellidoMaternoBdnsar",
    "fechaNacimiento",
    "genero",
    "entidadNacimiento",
    "curpBdnsar",
    "salarioDiarioIntegrado",
    "periodoPago",
    "indicadorRetiroDesempleo",
    "listaIcefasDisponiblesSaldo",
    "nombreImss",
    "nombreRenapo",
    "apellidoPaternoRenapo",
    "apellidoMaternoRenapo",
    "estatusCURPDuplicada",
    "listaCurpHistoricas"
})
public class ConsultarKardexSalida {

    @XmlElement(required = true)
    protected String resultadoOperacion;
    protected String diagnosticoProcesar;
    protected String nss;
    @XmlElement(required = true)
    protected String curp;
    protected String nombreBdnsar;
    protected String apellidoPaternoBdnsar;
    protected String apellidoMaternoBdnsar;
    protected String fechaNacimiento;
    protected String genero;
    protected String entidadNacimiento;
    protected String curpBdnsar;
    protected String salarioDiarioIntegrado;
    protected String periodoPago;
    protected String indicadorRetiroDesempleo;
    protected ListaIcefasDisponiblesSaldo listaIcefasDisponiblesSaldo;
    protected String nombreImss;
    protected String nombreRenapo;
    protected String apellidoPaternoRenapo;
    protected String apellidoMaternoRenapo;
    protected String estatusCURPDuplicada;
    protected CurpHistoricas listaCurpHistoricas;

    /**
     * Gets the value of the resultadoOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultadoOperacion() {
        return resultadoOperacion;
    }

    /**
     * Sets the value of the resultadoOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultadoOperacion(String value) {
        this.resultadoOperacion = value;
    }

    /**
     * Gets the value of the diagnosticoProcesar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosticoProcesar() {
        return diagnosticoProcesar;
    }

    /**
     * Sets the value of the diagnosticoProcesar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosticoProcesar(String value) {
        this.diagnosticoProcesar = value;
    }

    /**
     * Gets the value of the nss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNss() {
        return nss;
    }

    /**
     * Sets the value of the nss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNss(String value) {
        this.nss = value;
    }

    /**
     * Gets the value of the curp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurp() {
        return curp;
    }

    /**
     * Sets the value of the curp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurp(String value) {
        this.curp = value;
    }

    /**
     * Gets the value of the nombreBdnsar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreBdnsar() {
        return nombreBdnsar;
    }

    /**
     * Sets the value of the nombreBdnsar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreBdnsar(String value) {
        this.nombreBdnsar = value;
    }

    /**
     * Gets the value of the apellidoPaternoBdnsar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoPaternoBdnsar() {
        return apellidoPaternoBdnsar;
    }

    /**
     * Sets the value of the apellidoPaternoBdnsar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoPaternoBdnsar(String value) {
        this.apellidoPaternoBdnsar = value;
    }

    /**
     * Gets the value of the apellidoMaternoBdnsar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoMaternoBdnsar() {
        return apellidoMaternoBdnsar;
    }

    /**
     * Sets the value of the apellidoMaternoBdnsar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoMaternoBdnsar(String value) {
        this.apellidoMaternoBdnsar = value;
    }

    /**
     * Gets the value of the fechaNacimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaNacimiento() {
        return fechaNacimiento;
    }

    /**
     * Sets the value of the fechaNacimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaNacimiento(String value) {
        this.fechaNacimiento = value;
    }

    /**
     * Gets the value of the genero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenero() {
        return genero;
    }

    /**
     * Sets the value of the genero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenero(String value) {
        this.genero = value;
    }

    /**
     * Gets the value of the entidadNacimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidadNacimiento() {
        return entidadNacimiento;
    }

    /**
     * Sets the value of the entidadNacimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidadNacimiento(String value) {
        this.entidadNacimiento = value;
    }

    /**
     * Gets the value of the curpBdnsar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurpBdnsar() {
        return curpBdnsar;
    }

    /**
     * Sets the value of the curpBdnsar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurpBdnsar(String value) {
        this.curpBdnsar = value;
    }

    /**
     * Gets the value of the salarioDiarioIntegrado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalarioDiarioIntegrado() {
        return salarioDiarioIntegrado;
    }

    /**
     * Sets the value of the salarioDiarioIntegrado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalarioDiarioIntegrado(String value) {
        this.salarioDiarioIntegrado = value;
    }

    /**
     * Gets the value of the periodoPago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodoPago() {
        return periodoPago;
    }

    /**
     * Sets the value of the periodoPago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodoPago(String value) {
        this.periodoPago = value;
    }

    /**
     * Gets the value of the indicadorRetiroDesempleo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorRetiroDesempleo() {
        return indicadorRetiroDesempleo;
    }

    /**
     * Sets the value of the indicadorRetiroDesempleo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorRetiroDesempleo(String value) {
        this.indicadorRetiroDesempleo = value;
    }

    /**
     * Gets the value of the listaIcefasDisponiblesSaldo property.
     * 
     * @return
     *     possible object is
     *     {@link ListaIcefasDisponiblesSaldo }
     *     
     */
    public ListaIcefasDisponiblesSaldo getListaIcefasDisponiblesSaldo() {
        return listaIcefasDisponiblesSaldo;
    }

    /**
     * Sets the value of the listaIcefasDisponiblesSaldo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaIcefasDisponiblesSaldo }
     *     
     */
    public void setListaIcefasDisponiblesSaldo(ListaIcefasDisponiblesSaldo value) {
        this.listaIcefasDisponiblesSaldo = value;
    }

    /**
     * Gets the value of the nombreImss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreImss() {
        return nombreImss;
    }

    /**
     * Sets the value of the nombreImss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreImss(String value) {
        this.nombreImss = value;
    }

    /**
     * Gets the value of the nombreRenapo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreRenapo() {
        return nombreRenapo;
    }

    /**
     * Sets the value of the nombreRenapo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreRenapo(String value) {
        this.nombreRenapo = value;
    }

    /**
     * Gets the value of the apellidoPaternoRenapo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoPaternoRenapo() {
        return apellidoPaternoRenapo;
    }

    /**
     * Sets the value of the apellidoPaternoRenapo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoPaternoRenapo(String value) {
        this.apellidoPaternoRenapo = value;
    }

    /**
     * Gets the value of the apellidoMaternoRenapo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoMaternoRenapo() {
        return apellidoMaternoRenapo;
    }

    /**
     * Sets the value of the apellidoMaternoRenapo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoMaternoRenapo(String value) {
        this.apellidoMaternoRenapo = value;
    }

    /**
     * Gets the value of the estatusCURPDuplicada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstatusCURPDuplicada() {
        return estatusCURPDuplicada;
    }

    /**
     * Sets the value of the estatusCURPDuplicada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstatusCURPDuplicada(String value) {
        this.estatusCURPDuplicada = value;
    }

    /**
     * Gets the value of the listaCurpHistoricas property.
     * 
     * @return
     *     possible object is
     *     {@link CurpHistoricas }
     *     
     */
    public CurpHistoricas getListaCurpHistoricas() {
        return listaCurpHistoricas;
    }

    /**
     * Sets the value of the listaCurpHistoricas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurpHistoricas }
     *     
     */
    public void setListaCurpHistoricas(CurpHistoricas value) {
        this.listaCurpHistoricas = value;
    }

}
