//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.09 at 12:03:57 PM CDT 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listaIcefasDisponiblesSaldo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listaIcefasDisponiblesSaldo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="icefasDisponible" type="{http://www.procesar.com.mx/ArquitecturaSW/DataTypes/tiposComunesProcesar/}alfaNumerico_3" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listaIcefasDisponiblesSaldo", propOrder = {
    "icefasDisponible"
})
public class ListaIcefasDisponiblesSaldo {

    protected List<String> icefasDisponible;

    /**
     * Gets the value of the icefasDisponible property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icefasDisponible property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcefasDisponible().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIcefasDisponible() {
        if (icefasDisponible == null) {
            icefasDisponible = new ArrayList<String>();
        }
        return this.icefasDisponible;
    }

	/**
	 * @param icefasDisponible the icefasDisponible to set
	 */
	public void setIcefasDisponible(List<String> icefasDisponible) {
		this.icefasDisponible = icefasDisponible;
	}
    
    

}
