//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 12:26:30 PM CST 
//

package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo;

import java.io.Serializable;
import java.util.List;

/**
 * <p>
 * Java class for LayoutRespuestaHistoricoRetiros complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutRespuestaHistoricoRetiros"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="claveAforeRetiroReintegro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="diagnosticoProceso" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaRetiroReintegro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="montoRetiroReintegro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nssTrabajador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numeroResolucion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resultadoOperacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="semanasDescontadosRecuperadas" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="tipoPrestacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="valorDiaReintegrar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class RespuestaHistoricoRetiros implements Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 4099126085611598833L;

	/**
	 * claveAforeRetiroReintegro
	 */
	protected String claveAforeRetiroReintegro;

	/**
	 * diagnosticoProceso
	 */
	protected String diagnosticoProceso;

	/**
	 * fechaRetiroReintegro
	 */
	protected String fechaRetiroReintegro;

	/**
	 * montoRetiroReintegro
	 */
	protected String montoRetiroReintegro;

	/**
	 * nssTrabajador
	 */
	protected String nssTrabajador;

	/**
	 * numeroResolucion
	 */
	protected String numeroResolucion;

	/**
	 * semanasDescontadosRecuperadas
	 */
	protected String semanasDescontadosRecuperadas;

	/**
	 * tipoPrestacion
	 */
	protected String tipoPrestacion;

	/**
	 * valorDiaReintegrar
	 */
	protected String valorDiaReintegrar;

	/**
	 * descripcionAfore
	 */
	protected String descripcionAfore;

	/**
	 * rtphre
	 */
	protected Rtphre rtphre;

	/**
	 * rtpseg
	 */
	protected List<Rtpseg> rtpseg;

	/**
	 * descripcion diagnosticoProceso
	 */
	protected String diagnosticoProcesoDescripcion;

	/**
	 * descripcion tipoPrestacion
	 */
	protected String tipoPrestacionDescripcion;

	/**
	 * fechaRetiroReintegro para la vista
	 */
	protected String fechaRetiroReintegroVista;

	/**
	 * montoRestante
	 */
	protected String montoRestante;

	/**
	 * semanasReintegradas
	 */
	protected String semanasReintegradas;

	/**
	 * semanasRestantes
	 */
	protected String semanasRestantes;

	/**
	 * Montos confirmados
	 */
	protected List<ConfirmacionMonto> montosConfirmados;

	/**
	 * Gets the value of the claveAforeRetiroReintegro property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClaveAforeRetiroReintegro() {
		return claveAforeRetiroReintegro;
	}

	/**
	 * Sets the value of the claveAforeRetiroReintegro property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClaveAforeRetiroReintegro(String value) {
		this.claveAforeRetiroReintegro = value;
	}

	/**
	 * Gets the value of the diagnosticoProceso property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDiagnosticoProceso() {
		return diagnosticoProceso;
	}

	/**
	 * Sets the value of the diagnosticoProceso property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDiagnosticoProceso(String value) {
		this.diagnosticoProceso = value;
	}

	/**
	 * Gets the value of the fechaRetiroReintegro property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFechaRetiroReintegro() {
		return fechaRetiroReintegro;
	}

	/**
	 * Sets the value of the fechaRetiroReintegro property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFechaRetiroReintegro(String value) {
		this.fechaRetiroReintegro = value;
	}

	/**
	 * Gets the value of the montoRetiroReintegro property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMontoRetiroReintegro() {
		return montoRetiroReintegro;
	}

	/**
	 * Sets the value of the montoRetiroReintegro property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMontoRetiroReintegro(String value) {
		this.montoRetiroReintegro = value;
	}

	/**
	 * Gets the value of the nssTrabajador property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNssTrabajador() {
		return nssTrabajador;
	}

	/**
	 * Sets the value of the nssTrabajador property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNssTrabajador(String value) {
		this.nssTrabajador = value;
	}

	/**
	 * Gets the value of the numeroResolucion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumeroResolucion() {
		return numeroResolucion;
	}

	/**
	 * Sets the value of the numeroResolucion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumeroResolucion(String value) {
		this.numeroResolucion = value;
	}

	/**
	 * Gets the value of the semanasDescontadosRecuperadas property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSemanasDescontadosRecuperadas() {
		return semanasDescontadosRecuperadas;
	}

	/**
	 * Sets the value of the semanasDescontadosRecuperadas property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSemanasDescontadosRecuperadas(String value) {
		this.semanasDescontadosRecuperadas = value;
	}

	/**
	 * Gets the value of the tipoPrestacion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTipoPrestacion() {
		return tipoPrestacion;
	}

	/**
	 * Sets the value of the tipoPrestacion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTipoPrestacion(String value) {
		this.tipoPrestacion = value;
	}

	/**
	 * Gets the value of the valorDiaReintegrar property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValorDiaReintegrar() {
		return valorDiaReintegrar;
	}

	/**
	 * Sets the value of the valorDiaReintegrar property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValorDiaReintegrar(String value) {
		this.valorDiaReintegrar = value;
	}

	/**
	 * @return el atributo descripcionAfore
	 */
	public String getDescripcionAfore() {
		return descripcionAfore;
	}

	/**
	 * @param descripcionAfore
	 *            parametro descripcionAfore a actualizar
	 */
	public void setDescripcionAfore(String descripcionAfore) {
		this.descripcionAfore = descripcionAfore;
	}

	/**
	 * @return el atributo rtphre
	 */
	public Rtphre getRtphre() {
		return rtphre;
	}

	/**
	 * @param rtphre
	 *            parametro rtphre a actualizar
	 */
	public void setRtphre(Rtphre rtphre) {
		this.rtphre = rtphre;
	}

	/**
	 * @return el atributo rtpseg
	 */
	public List<Rtpseg> getRtpseg() {
		return rtpseg;
	}

	/**
	 * @param rtpseg
	 *            parametro rtpseg a actualizar
	 */
	public void setRtpseg(List<Rtpseg> rtpseg) {
		this.rtpseg = rtpseg;
	}

	/**
	 * @return el atributo fechaRetiroReintegroVista
	 */
	public String getFechaRetiroReintegroVista() {
		return fechaRetiroReintegroVista;
	}

	/**
	 * @param fechaRetiroReintegroVista
	 *            parametro fechaRetiroReintegroVista a actualizar
	 */
	public void setFechaRetiroReintegroVista(String fechaRetiroReintegroVista) {
		this.fechaRetiroReintegroVista = fechaRetiroReintegroVista;
	}

	/**
	 * @return el atributo diagnosticoProcesoDescripcion
	 */
	public String getDiagnosticoProcesoDescripcion() {
		return diagnosticoProcesoDescripcion;
	}

	/**
	 * @param diagnosticoProcesoDescripcion
	 *            parametro diagnosticoProcesoDescripcion a actualizar
	 */
	public void setDiagnosticoProcesoDescripcion(String diagnosticoProcesoDescripcion) {
		this.diagnosticoProcesoDescripcion = diagnosticoProcesoDescripcion;
	}

	/**
	 * @return el atributo tipoPrestacionDescripcion
	 */
	public String getTipoPrestacionDescripcion() {
		return tipoPrestacionDescripcion;
	}

	/**
	 * @param tipoPrestacionDescripcion
	 *            parametro tipoPrestacionDescripcion a actualizar
	 */
	public void setTipoPrestacionDescripcion(String tipoPrestacionDescripcion) {
		this.tipoPrestacionDescripcion = tipoPrestacionDescripcion;
	}

	/**
	 * @return el atributo montoRestante
	 */
	public String getMontoRestante() {
		return montoRestante;
	}

	/**
	 * @param montoRestante
	 *            parametro montoRestante a actualizar
	 */
	public void setMontoRestante(String montoRestante) {
		this.montoRestante = montoRestante;
	}

	/**
	 * @return el atributo semanasRestantes
	 */
	public String getSemanasRestantes() {
		return semanasRestantes;
	}

	/**
	 * @param semanasRestantes
	 *            parametro semanasRestantes a actualizar
	 */
	public void setSemanasRestantes(String semanasRestantes) {
		this.semanasRestantes = semanasRestantes;
	}

	/**
	 * Obtener montosConfirmados
	 */
	public List<ConfirmacionMonto> getMontosConfirmados() {
		return montosConfirmados;
	}

	/**
	 * Setear montosConfirmados
	 */
	public void setMontosConfirmados(List<ConfirmacionMonto> montosConfirmados) {
		this.montosConfirmados = montosConfirmados;
	}

	/**
	 * Obtener semanasReintegradas
	 */
	public String getSemanasReintegradas() {
		return semanasReintegradas;
	}

	/**
	 * Setear semanasReintegradas
	 */
	public void setSemanasReintegradas(String semanasReintegradas) {
		this.semanasReintegradas = semanasReintegradas;
	}

	/*
	 * La documentación de este método se encuentra en la clase o interface que
	 * lo declara (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("RespuestaHistoricoRetiros [claveAforeRetiroReintegro=");
		builder.append(claveAforeRetiroReintegro);
		builder.append(", diagnosticoProceso=");
		builder.append(diagnosticoProceso);
		builder.append(", fechaRetiroReintegro=");
		builder.append(fechaRetiroReintegro);
		builder.append(", montoRetiroReintegro=");
		builder.append(montoRetiroReintegro);
		builder.append(", nssTrabajador=");
		builder.append(nssTrabajador);
		builder.append(", numeroResolucion=");
		builder.append(numeroResolucion);
		builder.append(", semanasDescontadosRecuperadas=");
		builder.append(semanasDescontadosRecuperadas);
		builder.append(", tipoPrestacion=");
		builder.append(tipoPrestacion);
		builder.append(", valorDiaReintegrar=");
		builder.append(valorDiaReintegrar);
		builder.append(", descripcionAfore=");
		builder.append(descripcionAfore);
		builder.append(", rtphre=");
		builder.append(rtphre);
		builder.append(", rtpseg=");
		builder.append(rtpseg);
		builder.append(", diagnosticoProcesoDescripcion=");
		builder.append(diagnosticoProcesoDescripcion);
		builder.append(", tipoPrestacionDescripcion=");
		builder.append(tipoPrestacionDescripcion);
		builder.append(", fechaRetiroReintegroVista=");
		builder.append(fechaRetiroReintegroVista);
		builder.append(", montoRestante=");
		builder.append(montoRestante);
		builder.append(", semanasRestantes=");
		builder.append(semanasRestantes);
		builder.append("]");
		return builder.toString();
	}

}
