//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 12:26:30 PM CST 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonInclude;



/**
 * <p>Java class for LayoutRespuestaNotificacionReintegro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutRespuestaNotificacionReintegro"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="diagnosticoProceso" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaPagoReintegro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fechaRetiro" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="montoReintegrar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nssTrabajador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numeroResolucion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="numeroSemanasAReintegrar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resultadoOperacion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class RespuestaNotificacionReintegro implements Serializable {

   /**
	 * serial VersionUID
	 */
	private static final long serialVersionUID = 256582709382219701L;
	
		protected String diagnosticoProceso;
    protected String fechaPagoReintegro;
    protected String fechaRetiro;
    protected String montoReintegrar;
    protected String nssTrabajador;
    protected String numeroResolucion;
    protected String numeroSemanasAReintegrar;
    protected String resultadoOperacion;

    /**
     * Gets the value of the diagnosticoProceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosticoProceso() {
        return diagnosticoProceso;
    }

    /**
     * Sets the value of the diagnosticoProceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosticoProceso(String value) {
        this.diagnosticoProceso = value;
    }

    /**
     * Gets the value of the fechaPagoReintegro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaPagoReintegro() {
        return fechaPagoReintegro;
    }

    /**
     * Sets the value of the fechaPagoReintegro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaPagoReintegro(String value) {
        this.fechaPagoReintegro = value;
    }

    /**
     * Gets the value of the fechaRetiro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaRetiro() {
        return fechaRetiro;
    }

    /**
     * Sets the value of the fechaRetiro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaRetiro(String value) {
        this.fechaRetiro = value;
    }

    /**
     * Gets the value of the montoReintegrar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMontoReintegrar() {
        return montoReintegrar;
    }

    /**
     * Sets the value of the montoReintegrar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMontoReintegrar(String value) {
        this.montoReintegrar = value;
    }

    /**
     * Gets the value of the nssTrabajador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNssTrabajador() {
        return nssTrabajador;
    }

    /**
     * Sets the value of the nssTrabajador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNssTrabajador(String value) {
        this.nssTrabajador = value;
    }

    /**
     * Gets the value of the numeroResolucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroResolucion() {
        return numeroResolucion;
    }

    /**
     * Sets the value of the numeroResolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroResolucion(String value) {
        this.numeroResolucion = value;
    }

    /**
     * Gets the value of the numeroSemanasAReintegrar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroSemanasAReintegrar() {
        return numeroSemanasAReintegrar;
    }

    /**
     * Sets the value of the numeroSemanasAReintegrar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroSemanasAReintegrar(String value) {
        this.numeroSemanasAReintegrar = value;
    }

    /**
     * Gets the value of the resultadoOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultadoOperacion() {
        return resultadoOperacion;
    }

    /**
     * Sets the value of the resultadoOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultadoOperacion(String value) {
        this.resultadoOperacion = value;
    }

		/* La documentación de este método se encuentra en la clase o interface que
		 * lo declara  (non-Javadoc)
		 * @see java.lang.Object#toString()
		 */
		@Override
		public String toString() {
			StringBuilder builder = new StringBuilder();
			builder.append("RespuestaNotificacionReintegro [getDiagnosticoProceso()=");
			builder.append(getDiagnosticoProceso());
			builder.append(", getFechaPagoReintegro()=");
			builder.append(getFechaPagoReintegro());
			builder.append(", getFechaRetiro()=");
			builder.append(getFechaRetiro());
			builder.append(", getMontoReintegrar()=");
			builder.append(getMontoReintegrar());
			builder.append(", getNssTrabajador()=");
			builder.append(getNssTrabajador());
			builder.append(", getNumeroResolucion()=");
			builder.append(getNumeroResolucion());
			builder.append(", getNumeroSemanasAReintegrar()=");
			builder.append(getNumeroSemanasAReintegrar());
			builder.append(", getResultadoOperacion()=");
			builder.append(getResultadoOperacion());
			builder.append("]");
			return builder.toString();
		}

}
