//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 04:02:59 PM CDT 
//


package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.modelo;

import java.io.Serializable;

public class ValidarSolicitudCertificacionAforeContrato implements Serializable  {

    /**
	 * Serial Id
	 */
	private static final long serialVersionUID = 7474243231427255360L;
    /**
     * cuerpo
     */
    private ValidarSolicitudCertificacionAforeEntrada cuerpo;


    /**
     * Gets the value of the cuerpo property.
     * 
     * @return
     *     possible object is
     *     {@link GenerarCertificadoTraspasosEntrada }
     *     
     */
    public ValidarSolicitudCertificacionAforeEntrada getCuerpo() {
        return cuerpo;
    }

    /**
     * Sets the value of the cuerpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenerarCertificadoTraspasosEntrada }
     *     
     */
    public void setCuerpo(ValidarSolicitudCertificacionAforeEntrada cuerpo) {
        this.cuerpo = cuerpo;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("ValidarSolicitudCertificacionAforeContrato [");
		builder.append("cuerpo=");
		builder.append(cuerpo);
		builder.append("]");
		return builder.toString();
	}

}
