
package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificarAutenticacionPort", targetNamespace = "http://www.procesar.com.mx/ServiciosInternos/PortalServicios/AutenticacionINE/NotificarAutenticacion/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificarAutenticacionPort {


    /**
     * 
     * @param notificarAutenticacionRequest
     * @return
     *     returns mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.ws.NotificarAutenticacionRespuesta
     */
    @WebMethod(action = "http://www.procesar.com.mx/ServiciosInternos/PortalServicios/Comparador/notificarAutenticacion/")
    @WebResult(name = "notificarAutenticacionResponse", targetNamespace = "http://www.procesar.com.mx/ServiciosInternos/PortalServicios/AutenticacionINE/notificarAutenticacion/", partName = "notificarAutenticacionResponse")
    public NotificarAutenticacionRespuesta notificarAutenticacion(
        @WebParam(name = "notificarAutenticacionRequest", targetNamespace = "http://www.procesar.com.mx/ServiciosInternos/PortalServicios/AutenticacionINE/notificarAutenticacion/", partName = "notificarAutenticacionRequest")
        NotificarAutenticacionContrato notificarAutenticacionRequest);

}
