
package mx.com.procesar.aplicaciones.traspasos.pulssar.servicios.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificarAutenticacion", targetNamespace = "http://www.procesar.com.mx/ServiciosInternos/PortalServicios/AutenticacionINE/NotificarAutenticacion/", wsdlLocation = "http://172.21.66.90/ServiciosInternos/NotificarAutenticacion?wsdl")
public class NotificarAutenticacion
    extends Service
{

    private final static URL NOTIFICARAUTENTICACION_WSDL_LOCATION;
    private final static WebServiceException NOTIFICARAUTENTICACION_EXCEPTION;
    private final static QName NOTIFICARAUTENTICACION_QNAME = new QName("http://www.procesar.com.mx/ServiciosInternos/PortalServicios/AutenticacionINE/NotificarAutenticacion/", "NotificarAutenticacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.21.66.90/ServiciosInternos/NotificarAutenticacion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICARAUTENTICACION_WSDL_LOCATION = url;
        NOTIFICARAUTENTICACION_EXCEPTION = e;
    }

    public NotificarAutenticacion() {
        super(__getWsdlLocation(), NOTIFICARAUTENTICACION_QNAME);
    }

    public NotificarAutenticacion(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICARAUTENTICACION_QNAME, features);
    }

    public NotificarAutenticacion(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICARAUTENTICACION_QNAME);
    }

    public NotificarAutenticacion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICARAUTENTICACION_QNAME, features);
    }

    public NotificarAutenticacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificarAutenticacion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificarAutenticacionPort
     */
    @WebEndpoint(name = "NotificarAutenticacionPort")
    public NotificarAutenticacionPort getNotificarAutenticacionPort() {
        return super.getPort(new QName("http://www.procesar.com.mx/ServiciosInternos/PortalServicios/AutenticacionINE/NotificarAutenticacion/", "NotificarAutenticacionPort"), NotificarAutenticacionPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificarAutenticacionPort
     */
    @WebEndpoint(name = "NotificarAutenticacionPort")
    public NotificarAutenticacionPort getNotificarAutenticacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.procesar.com.mx/ServiciosInternos/PortalServicios/AutenticacionINE/NotificarAutenticacion/", "NotificarAutenticacionPort"), NotificarAutenticacionPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICARAUTENTICACION_EXCEPTION!= null) {
            throw NOTIFICARAUTENTICACION_EXCEPTION;
        }
        return NOTIFICARAUTENTICACION_WSDL_LOCATION;
    }

}
