#${{ github.run_number }} al nuevo nombre del artefacto generado antes de la implementación. 
#Esto incorporará un número de versión único en el nombre del artefacto, que se basará en el 
#número de ejecución del flujo de trabajo actual en GitHub Actions. 
#De esta manera, cada implementación generará un artefacto con un nombre único que refleje la versión del flujo de trabajo.


name: CI pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  fortify_analisis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fortify ScanCentral Scan
        uses: ./.github/workflows/fortify.yml
        
  build:
    needs: [fortify_analisis]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8', '11']  # Definimos una matriz con las versiones de Java
        maven-version : ['3.3', '3.8.1'] # Definimos una matriz con las versiones de Maven
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2  
        with:
           java-version: ${{ matrix.java-version }} #version de java.
           distribution: ${{ matrix.java-version == '11' && 'adopt-openj9' || 'adopt' }}
      - name: Set up Maven
        run: |
          if [[ "${{ matrix.maven-version }}" == "3.3" ]]; then
             wget -q http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
             tar xf apache-maven-3.3.9-bin.tar.gz
             export PATH="$PWD/apache-maven-3.3.9/bin:$PATH"
          else
             wget -q http://archive.apache.org/dist/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
             tar xf apache-maven-3.8.1-bin.tar.gz
             export PATH="$PWD/apache-maven-3.8.1/bin:$PATH"
          fi
          
      - name: Download settings.xml
        run: |
            mkdir -p /home/runner/.m2/repository
            curl -o /home/runner/.m2/repository/settings.xml -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} https://nexus.james.lab.zivra.com/repository/cchang_artifacts/archivos/settings/2.0/settings-2.0.xml
            cat /home/runner/.m2/repository/settings.xml
    
      - name: Build application con Maven
        run:  mvn clean install

      - name: Ejecutar Action personalizada para versionamiento
        uses: ./.github/actions/action_tag.yml

      - name: Captura salida de la accion
        run: |
          output_content=$(<output.txt)
          echo "Version: $output_content"
 
      - name: Change Artifact Name
        run: |
          mvn build-helper:change-project-artifact -DnewName=nombre-del-artifact-aqui-con-version-$Version

      - name: Sonarqube Scan
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=pry-comunes \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://servidor-sonarqube.com \
            -Dsonar.login=$SONARQUBE_TOKEN || true
          
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \ 
             -Dsonar.organization=cchang1611 \ 
             -Dsonar.projectKey=cchang1611_demo_clientep \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=$SONAR_TOKEN
             
      - name: Deploy to Nexus #Guarda el artefacto generado en Nexus
        run: |
          mvn deploy \
            -DskipTests=true \  #Opcional
            -DaltDeploymentRepository=nexus::default::https://nexus.procesar.mx \
            -Dusername=usuario-nexus \
            -Dpassword=contraseña-nexus
      
